rename_dict = {
    'a1' : 'Vallgatan',
    'a2' : 'Sofias garden',
    'a3' : 'Guldhedstorget',
    'a4' : 'Svingeln',
    'a5' : 'Kungsparken',
    'a6' : 'Parking Lot',
    'a7' : 'Hisingen Million-programme',
    'a8' : 'Behind GVC',
    'a9' : 'Near Chalmers',
    'a10' : 'Functionalism Kville',
    'a11' : 'Cemetery',
    'a12' : 'Kungsladugård',
    'a13' : 'New Kville',
    'a14' : 'Old Kville',
    'a15' : 'Villa Hisingen',
    'a16' : 'Fredriks Garden',
    'a17' : 'Slottskogen',
    'a18' : 'Chapmans Torg',
    'a19' : 'Vasa',
    'a20' : 'Fredriks Friend',
}